### ISSUE TITLE
Add footprint data to schema

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/buildings#25]
Need to include the footprint in the [building.json](https://github.com/Chicago/buildings/wiki/Example-of-building.json) schema. Likely, can use geojson to render the building footprint and include it in the file. [Here is an example](https://github.com/Chicago/osd-building-footprints) of what buildings render as geojson.

**Comment by nicklucius** [comment]
I hit a slight stumbling block with this. The `writeOGR()` function in the `rgdal` package cannot handle the nested data. Here are some choices I can think of. Maybe the best choice will become clearer after discussing with the OpenGrid team.

- Keep `building.json` as a `json` intead of a `geojson`. Footprints can be linked to each building record on the fly.

- Write our own code to create a `geojson` file.

- Suggest the feature to the `rgdal` developers. - [github ](https://github.com/cran/rgdal ) - [homepage](http://www.gdal.org/)

```
> writeOGR(combinedGeoJSON, "buildings-test.geojson", "OGRGeoJSON", driver="GeoJSON")
Error in writeOGR(combinedGeoJSON, "buildings-test.geojson", "OGRGeoJSON",  : 
  Can't convert columns of class: list; column names: pins,area,areaRatio,pinsFinal,annual_sale.alltime,annual_sale.pastyear,annual_sale.past90days,annual_sale.past30days,annual_sale,scavenger_sale.alltime,scavenger_sale.pastyear,scavenger_sale.past90days,scavenger_sale.past30days,scavenger_sale,demoBldg.alltime,demoBldg.pastyear,demoBldg.past90days,demoBldg.past30days,demoBldg,demoPIN.alltime,demoPIN.pastyear,demoPIN.past90days,demoPIN.past30days,demoPIN,vacant311Bldg,vacant311PIN
```

**Comment by tomschenkjr** [comment]
So, the only geojson aspect we need is the geo-coordinates of the footprint. One field can be the coordinates, but otherwise follows the normal layout of a `.json` file. Strikes me as the easiest solution, but certainly I think the developers will help shape the best solution.

**Comment by nicklucius** [comment]
Good idea.

**Comment by tomschenkjr** [comment]
After the meeting last week, I'm curious if it makes sense to create a prototype layout--as above--that uses geojson coordinates in the field for and otherwise `.json` layout? We can then circulate it to Jesse, Rod, and the team for feedback.

**Comment by nicklucius** [comment]
Sounds like a good next step. I'll get it going.

**Comment by nicklucius** [comment]
I've added the footprint data to the ```building.json``` example file [here](https://github.com/Chicago/buildings/wiki/Example-of-building.json). There is probably more information than needed, but it was all provided by the R Package. 

[Here is some documentation](https://www.rdocumentation.org/packages/sp/versions/1.2-5/topics/Polygon-class) on the Spatial Polygon datatype in R, which tracks to the way it is structured in the example ```json``` file.
